"use client";

import LanguageSwitcher from "../../components/LanguageSwitcher";
import { FREE_DAILY_LIMIT } from "../../lib/config";
import { useI18n } from "../../lib/i18n";

const SECTIONS = {
  en: [
    ["1. The service", "NotesBang scores and rewrites text you provide (pasted, .docx, .txt, .md), using third-party AI models. By using the service you agree to these terms."],
    ["2. Accounts & free usage", `You need an account with a verified email. During early access the service is free, limited to ${FREE_DAILY_LIMIT} analyses per day per account and 3000 characters per piece. Accounts created to abuse the free tier may be suspended.`],
    ["3. Your content & AI processing", "You keep ownership of your text. To score and rewrite it, the content is sent to a third-party AI model for processing. You confirm you have the right to process the content and that it is lawful."],
    ["4. Data used to improve the service", "By default, your anonymized copy and its scores help us learn what makes copy effective. You can turn this off per document or at any time; see the Privacy Policy."],
    ["5. Acceptable use", "Do not upload unlawful or infringing material, attempt unauthorized access, overload the service, or use it to produce defamatory or hateful content."],
    ["6. Generated content & disclaimers", "Scores and rewrites are generated by AI and may contain errors. You are responsible for reviewing and fact-checking before publishing. The service is provided \"as is\" without warranties, and to the extent permitted by law NotesBang is not liable for indirect or consequential damages."],
    ["7. Termination & changes", "We may suspend accounts that violate these terms and may update these terms by posting a new version here. You may stop using the service and delete your documents or account at any time."],
    ["8. Contact & law", "Questions: reach us from inside the product. Governing law and contact details will be finalized before public launch."],
  ],
  zh: [
    ["1. 服务内容", "NotesBang 使用第三方 AI 模型，对你提供的文本（粘贴、.docx、.txt、.md）进行评分与改写。使用本服务即表示你同意本条款。"],
    ["2. 账号与免费使用", `你需要一个已验证邮箱的账号。早期体验期免费，限制为每账号每天 ${FREE_DAILY_LIMIT} 次分析、单篇不超过 3000 字。滥用免费额度的账号可能被暂停。`],
    ["3. 你的内容与 AI 处理", "你保留文本的所有权。为进行评分与改写，内容会发送给第三方 AI 模型处理。你确认有权处理该内容且内容合法。"],
    ["4. 用于改进服务的数据", "默认情况下，你的匿名文案及其评分会帮助我们总结“什么样的文案更有效”。你可以对单篇或随时关闭；详见隐私政策。"],
    ["5. 可接受使用", "请勿上传违法或侵权内容、尝试未授权访问、滥用或过载服务，或用其生成诽谤、仇恨等违规内容。"],
    ["6. 生成内容与免责", "评分与改写由 AI 生成，可能存在错误。发布前请自行审核与核对事实。本服务按“现状”提供、不附带任何担保；在法律允许范围内，NotesBang 不对间接或后果性损失负责。"],
    ["7. 终止与变更", "我们可能暂停违反本条款的账号，并可通过在本页发布新版本来更新条款。你可随时停止使用并删除文档或账号。"],
    ["8. 联系与法律适用", "如有疑问，可在产品内联系我们。适用法律与联系方式将在正式上线前确定。"],
  ],
} as const;

export default function TermsPage() {
  const { locale, t } = useI18n();
  const sections = SECTIONS[locale] ?? SECTIONS.en;
  return (
    <main className="min-h-full bg-white font-sans text-zinc-900 antialiased">
      <header className="sticky top-0 z-20 border-b border-black/5 bg-white/80 backdrop-blur-md">
        <div className="mx-auto flex h-14 w-full max-w-3xl items-center justify-between px-6">
          <a href="/" className="flex items-center gap-2 text-[15px] font-semibold tracking-tight">
            <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-zinc-800 to-zinc-950 text-sm font-bold text-white">NB</span>
            {t("common.app_name")}
          </a>
          <div className="flex items-center gap-3">
            <LanguageSwitcher />
            <a href="/studio" className="rounded-full bg-zinc-900 px-4 py-1.5 text-sm font-medium text-white hover:bg-zinc-700">
              {locale === "zh" ? "打开工作台" : "Open Studio"}
            </a>
          </div>
        </div>
      </header>
      <article className="mx-auto max-w-3xl px-6 py-14">
        <h1 className="text-3xl font-semibold tracking-tight">{locale === "zh" ? "使用条款" : "Terms of Use"}</h1>
        <p className="mt-2 text-sm text-zinc-400">NotesBang · 2026-09-10</p>
        <div className="mt-8 space-y-6 text-[15px] leading-relaxed text-zinc-600">
          {sections.map(([title, body]) => (
            <section key={title}>
              <h2 className="text-[17px] font-semibold text-zinc-900">{title}</h2>
              <p className="mt-1.5">{body}</p>
            </section>
          ))}
        </div>
      </article>
    </main>
  );
}
