import type { ReactNode } from "react";

export default function TermsPage() {
  return (
    <main className="min-h-full bg-white font-sans text-zinc-900 antialiased">
      <header className="sticky top-0 z-20 border-b border-black/5 bg-white/80 backdrop-blur-md">
        <div className="mx-auto flex h-14 w-full max-w-3xl items-center justify-between px-6">
          <a href="/" className="flex items-center gap-2 text-[15px] font-semibold tracking-tight">
            <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-zinc-800 to-zinc-950 text-sm font-bold text-white">
              NB
            </span>
            NotesBang
          </a>
          <a href="/app" className="rounded-full bg-zinc-900 px-4 py-1.5 text-sm font-medium text-white hover:bg-zinc-700">
            Open the app
          </a>
        </div>
      </header>

      <article className="mx-auto max-w-3xl px-6 py-14">
        <p className="text-xs font-medium uppercase tracking-widest text-zinc-400">Legal</p>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight">Terms of Use</h1>
        <p className="mt-2 text-sm text-zinc-400">Last updated: 2026-09-09 · NotesBang</p>

        <div className="mt-8 space-y-6 text-[15px] leading-relaxed text-zinc-600">
          <Section title="1. The service">
            NotesBang turns uploaded presentations (currently PowerPoint .pptx files) into
            suggested speaker notes using third-party AI models. By using the service you agree to
            these terms.
          </Section>
          <Section title="2. Accounts & the free preview">
            You need an account with a verified email. Each account receives a one-time free
            preview covering a single deck of up to two slides, including a limited number of
            regenerations. Accounts created to abuse free previews may be suspended.
          </Section>
          <Section title="3. Pricing & points">
            One point equals one generated slide at the base rate of US$0.50 per slide. Points are
            sold in the packs shown on the pricing page and are non-refundable except where
            required by law. Points are charged only for slides that are successfully generated;
            manual edits and exports never consume points. A generated slide that fails is not
            charged.
          </Section>
          <Section title="4. Content you submit & AI processing">
            You keep ownership of the documents you upload. To generate notes, file content is sent
            to and processed by third-party AI models. You confirm you own or have the right to
            process the content you upload and that it complies with applicable law. You may delete
            a project or your account at any time; we delete the associated data as described in our
            Privacy Policy.
          </Section>
          <Section title="5. Acceptable use">
            You agree not to: upload unlawful or infringing material; attempt to gain unauthorized
            access; probe, scrape, or overload the service; resell bulk generated output as an
            automated service; or use the service to produce content that is defamatory, hateful, or
            otherwise unlawful.
          </Section>
          <Section title="6. Generated content & disclaimers">
            Speaker notes are generated by AI and may contain errors, omissions, or inaccuracies.
            You are responsible for fact-checking and editing notes before use, and for how you use
            or present the output. The service is provided “as is”, without warranties of any kind,
            and to the maximum extent permitted by law NotesBang is not liable for indirect or
            consequential damages arising from its use.
          </Section>
          <Section title="7. Termination & changes">
            We may suspend accounts that violate these terms and may change these terms by posting an
            updated version here; continued use after changes means you accept them. You may stop
            using the service and delete your account at any time.
          </Section>
          <Section title="8. Contact & law">
            Questions or legal requests: contact us through the product. These terms are governed by
            the laws applicable where NotesBang is operated; details will be finalized before public
            launch.
          </Section>
        </div>
      </article>
    </main>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section>
      <h2 className="text-[17px] font-semibold text-zinc-900">{title}</h2>
      <p className="mt-1.5">{children}</p>
    </section>
  );
}
