"""baseline schema

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-09

Creates the full current schema from the SQLAlchemy metadata. Future changes
should be autogenerated as separate revisions (render_as_batch enabled for
SQLite compatibility).
"""
from __future__ import annotations

from alembic import op

import app.models  # noqa: F401  (register tables)
from app.db.base import Base

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
